server:
  port: 8086
  
spring:
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    platform: hsql
    url: jdbc:hsqldb:mem:eventdb;DB_CLOSE_DELAY=-1 
    username: sa
    password: sa
  jpa:
    database: hsql
    showSql: true
    hibernate:
      ddlAuto: ""
    properties: 
      hibernate.format_sql: true #